package au.edu.unsw.soacourse.dlservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-20T15:44:31.117+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://dlservice.soacourse.unsw.edu.au", name = "DLService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DLService {

    @WebResult(name = "DLValidateResponse", targetNamespace = "http://dlservice.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(operationName = "DLValidate", action = "http://dlservice.soacourse.unsw.edu.au/DLValidate")
    public DLValidateResponse dlValidate(
        @WebParam(partName = "parameters", name = "DLValidateRequest", targetNamespace = "http://dlservice.soacourse.unsw.edu.au")
        DLValidateRequest parameters
    ) throws DLValidateFaultMsg;
}
