package au.edu.unsw.soacourse.dlservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-20T15:44:31.164+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "DLService", 
                  wsdlLocation = "file:/C:/Users/X450JF/cs9322-Prac/workspace/COMP9322-Asst2/SOAPServices/src/main/resources/wsdl/DLService.wsdl",
                  targetNamespace = "http://dlservice.soacourse.unsw.edu.au") 
public class DLService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dlservice.soacourse.unsw.edu.au", "DLService");
    public final static QName DLServiceSOAP = new QName("http://dlservice.soacourse.unsw.edu.au", "DLServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/X450JF/cs9322-Prac/workspace/COMP9322-Asst2/SOAPServices/src/main/resources/wsdl/DLService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DLService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/X450JF/cs9322-Prac/workspace/COMP9322-Asst2/SOAPServices/src/main/resources/wsdl/DLService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DLService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DLService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DLService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DLService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DLService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DLService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns DLService
     */
    @WebEndpoint(name = "DLServiceSOAP")
    public DLService getDLServiceSOAP() {
        return super.getPort(DLServiceSOAP, DLService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DLService
     */
    @WebEndpoint(name = "DLServiceSOAP")
    public DLService getDLServiceSOAP(WebServiceFeature... features) {
        return super.getPort(DLServiceSOAP, DLService.class, features);
    }

}
