package au.edu.unsw.soacourse.backgroundcheck;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-31T22:54:34.982+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "BackgroundCheckService", 
                  wsdlLocation = "http://localhost:6060/ode/processes/BackgroundCheckService?wsdl",
                  targetNamespace = "http://soacourse.unsw.edu.au/backgroundcheck") 
public class BackgroundCheckService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soacourse.unsw.edu.au/backgroundcheck", "BackgroundCheckService");
    public final static QName BackgroundCheckPort = new QName("http://soacourse.unsw.edu.au/backgroundcheck", "BackgroundCheckPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:6060/ode/processes/BackgroundCheckService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BackgroundCheckService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:6060/ode/processes/BackgroundCheckService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BackgroundCheckService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BackgroundCheckService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackgroundCheckService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BackgroundCheckService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BackgroundCheckService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BackgroundCheckService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BackgroundCheckServicePortType
     */
    @WebEndpoint(name = "BackgroundCheckPort")
    public BackgroundCheckServicePortType getBackgroundCheckPort() {
        return super.getPort(BackgroundCheckPort, BackgroundCheckServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackgroundCheckServicePortType
     */
    @WebEndpoint(name = "BackgroundCheckPort")
    public BackgroundCheckServicePortType getBackgroundCheckPort(WebServiceFeature... features) {
        return super.getPort(BackgroundCheckPort, BackgroundCheckServicePortType.class, features);
    }

}
