package au.edu.unsw.soacourse.adrservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-19T17:33:03.052+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "ADRService", 
                  wsdlLocation = "file:/C:/Users/X450JF/cs9322-Prac/workspace/COMP9322-Asst2/SOAPServices/src/main/resources/wsdl/ADRService.wsdl",
                  targetNamespace = "http://adrservice.soacourse.unsw.edu.au") 
public class ADRService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://adrservice.soacourse.unsw.edu.au", "ADRService");
    public final static QName ADRServiceSOAP = new QName("http://adrservice.soacourse.unsw.edu.au", "ADRServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/X450JF/cs9322-Prac/workspace/COMP9322-Asst2/SOAPServices/src/main/resources/wsdl/ADRService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ADRService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/X450JF/cs9322-Prac/workspace/COMP9322-Asst2/SOAPServices/src/main/resources/wsdl/ADRService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ADRService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ADRService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ADRService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ADRService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ADRService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ADRService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ADRService
     */
    @WebEndpoint(name = "ADRServiceSOAP")
    public ADRService getADRServiceSOAP() {
        return super.getPort(ADRServiceSOAP, ADRService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ADRService
     */
    @WebEndpoint(name = "ADRServiceSOAP")
    public ADRService getADRServiceSOAP(WebServiceFeature... features) {
        return super.getPort(ADRServiceSOAP, ADRService.class, features);
    }

}
